runtime: python37

handlers:
  - url: /
    static_files: public/index.html
    upload: /

  - url: /(.*)/$
    static_files: public/\1/index.html
    upload: public/.*/index\.html

  - url: /
    static_dir: public
